id: I965E42B7
legacy_id: P007079
ocr_import_info:
  bdrc_scan_id: W8LS18157
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T20:41:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:07:22.102834+00:00'
last_modified: 2022-09-04 12:07:26.685727
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS18157
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS18157
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྨན་སྦྱོར་བདུད་རྩིའི་ཐིག་ལེ།
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6123922859250912
  ocr_word_median_confidence_index: 0.6499999761581421
quality: null
bases:
  I8LS18177:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS18177
      total_pages: 27
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS18177.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6123922859250912
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
