id: I965E42B7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T20:41:21+00:00'
last_modified: '2022-06-09T04:38:44.212193+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18157
  title: སྨན་སྦྱོར་བདུད་རྩིའི་ཐིག་ལེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ACD7:
      image_group_id: I8LS18177
      title: Volume 1 of sman sbyor bdud rtsi'i thig le/
      total_pages: 27
      order: 1
      base_file: ACD7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
