id: P007079
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18157
  title: སྨན་སྦྱོར་བདུད་རྩིའི་ཐིག་ལེ།
  author: ''
  volumes:
    b9d211443a7842f8b541648ee1723ed2:
      image_group_id: I8LS18177
      title: ''
      volume_number: 1
      total_pages: 27
ebook_metadata:
  title: སྨན་སྦྱོར་བདུད་རྩིའི་ཐིག་ལེ།
  author: ''
  sku: P007079
  cover: cover.jpg
  layers:
  - pagination
